name: 🚀 Deploy website on Staging/Demo Server
on:
  push:
    branches: [master]
obs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚚 Executing Git Pull on Server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.server_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}



